/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @Joa
 */
public class CalculatorApp extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorApp
     */
    public CalculatorApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        JBtnNum3 = new javax.swing.JButton();
        JBtnNum5 = new javax.swing.JButton();
        JBtnNum2 = new javax.swing.JButton();
        JBtnNum6 = new javax.swing.JButton();
        JBtnNum1 = new javax.swing.JButton();
        JBtnNum9 = new javax.swing.JButton();
        JBtnNum4 = new javax.swing.JButton();
        JBtnNum00 = new javax.swing.JButton();
        JBtnNum8 = new javax.swing.JButton();
        JBtnNum7 = new javax.swing.JButton();
        JBtnAdd = new javax.swing.JButton();
        JBtnNum0 = new javax.swing.JButton();
        JBtnEqual = new javax.swing.JButton();
        JBtnSubstract = new javax.swing.JButton();
        JBtnDecimal = new javax.swing.JButton();
        JBtnMultiply = new javax.swing.JButton();
        JBtnDivide = new javax.swing.JButton();
        JBtnAllClear = new javax.swing.JButton();
        JBtnDelete = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JTextResult = new javax.swing.JTextField();
        JLabelFnum = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JLabelOperation = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JLabelLength = new javax.swing.JLabel();
        JLabelFloat = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel3.setBackground(java.awt.Color.gray);

        JBtnNum3.setText("3");
        JBtnNum3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnNum3ActionPerformed(evt);
            }
        });

        JBtnNum5.setText("5");
        JBtnNum5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnNum5ActionPerformed(evt);
            }
        });

        JBtnNum2.setText("2");
        JBtnNum2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnNum2ActionPerformed(evt);
            }
        });

        JBtnNum6.setText("6");
        JBtnNum6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnNum6ActionPerformed(evt);
            }
        });

        JBtnNum1.setText("1");
        JBtnNum1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnNum1ActionPerformed(evt);
            }
        });
        JBtnNum1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JBtnNum1KeyTyped(evt);
            }
        });

        JBtnNum9.setText("9");
        JBtnNum9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnNum9ActionPerformed(evt);
            }
        });

        JBtnNum4.setText("4");
        JBtnNum4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnNum4ActionPerformed(evt);
            }
        });

        JBtnNum00.setText("00");
        JBtnNum00.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnNum00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnNum00ActionPerformed(evt);
            }
        });

        JBtnNum8.setText("8");
        JBtnNum8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnNum8ActionPerformed(evt);
            }
        });

        JBtnNum7.setText("7");
        JBtnNum7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnNum7ActionPerformed(evt);
            }
        });

        JBtnAdd.setText("+");
        JBtnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAddActionPerformed(evt);
            }
        });

        JBtnNum0.setText("0");
        JBtnNum0.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnNum0ActionPerformed(evt);
            }
        });

        JBtnEqual.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        JBtnEqual.setText("=");
        JBtnEqual.setBorderPainted(false);
        JBtnEqual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnEqualActionPerformed(evt);
            }
        });

        JBtnSubstract.setText("-");
        JBtnSubstract.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnSubstract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnSubstractActionPerformed(evt);
            }
        });

        JBtnDecimal.setText(".");
        JBtnDecimal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnDecimalActionPerformed(evt);
            }
        });

        JBtnMultiply.setText("X");
        JBtnMultiply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnMultiplyActionPerformed(evt);
            }
        });

        JBtnDivide.setText("/");
        JBtnDivide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnDivideActionPerformed(evt);
            }
        });

        JBtnAllClear.setText("AC");
        JBtnAllClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnAllClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAllClearActionPerformed(evt);
            }
        });

        JBtnDelete.setText("DEL");
        JBtnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnDeleteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arno Pro Caption", 3, 14)); // NOI18N
        jLabel3.setText("JMV Creations");

        jLabel4.setFont(new java.awt.Font("Arno Pro Caption", 3, 14)); // NOI18N
        jLabel4.setText("Do Not Forget The Semi-Colon");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(JBtnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBtnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(JBtnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBtnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JBtnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JBtnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBtnSubstract, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(JBtnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(JBtnNum00, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBtnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBtnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(JBtnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBtnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBtnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(JBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JBtnAllClear, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnAllClear, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBtnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBtnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBtnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnSubstract, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBtnNum00, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JBtnDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(JBtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        JTextResult.setEditable(false);
        JTextResult.setBackground(java.awt.Color.darkGray);
        JTextResult.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        JTextResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        JTextResult.setText("0");
        JTextResult.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JTextResult.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JTextResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextResultActionPerformed(evt);
            }
        });

        JLabelFnum.setBackground(java.awt.Color.darkGray);
        JLabelFnum.setForeground(new java.awt.Color(204, 204, 204));
        JLabelFnum.setText("0");

        jLabel1.setBackground(java.awt.Color.darkGray);
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("CALCULATOR");

        JLabelOperation.setBackground(java.awt.Color.darkGray);
        JLabelOperation.setForeground(new java.awt.Color(204, 204, 204));
        JLabelOperation.setText("None");

        jLabel2.setBackground(java.awt.Color.darkGray);
        jLabel2.setFont(new java.awt.Font("Dotum", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("8 DIGITS");

        JLabelLength.setBackground(java.awt.Color.darkGray);
        JLabelLength.setForeground(new java.awt.Color(204, 204, 204));
        JLabelLength.setText("0");

        JLabelFloat.setForeground(new java.awt.Color(204, 204, 204));
        JLabelFloat.setText("false");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JLabelFnum, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(JLabelOperation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(JLabelFloat)
                                .addGap(63, 63, 63)
                                .addComponent(JLabelLength, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2))
                            .addComponent(JTextResult, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextResult, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabelFnum)
                    .addComponent(JLabelOperation)
                    .addComponent(JLabelLength)
                    .addComponent(JLabelFloat))
                .addGap(1, 1, 1)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnNum3ActionPerformed
        // TODO add your handling code here:
       String Length = JLabelLength.getText();
        if(Length.equals("0")){
            JTextResult.setText("3");
        }
        
        String nextNum = JTextResult.getText();
        String Opr = JLabelOperation.getText();
        int digitlength = nextNum.length();
        String newdigitLength = String.valueOf(digitlength);
        JLabelLength.setText(newdigitLength);
        
        if(!(nextNum.equals("0"))&& Opr.equals("+")||Opr.equals("-")||Opr.equals("*")||Opr.equals("/")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "3");
            }
        }else if(!(nextNum.equals("0"))&&digitlength<=8&& Opr.equals("None")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "3");
            }
        }
    }//GEN-LAST:event_JBtnNum3ActionPerformed

    private void JTextResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextResultActionPerformed

    private void JBtnNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnNum1ActionPerformed
        // TODO add your handling code here:
        String Length = JLabelLength.getText();
        if(Length.equals("0")){
            JTextResult.setText("1");
        }
        
        String nextNum = JTextResult.getText();
        String Opr = JLabelOperation.getText();
        int digitlength = nextNum.length();
        String newdigitLength = String.valueOf(digitlength);
        JLabelLength.setText(newdigitLength);
        
        if(!(nextNum.equals("0"))&& Opr.equals("+")||Opr.equals("-")||Opr.equals("*")||Opr.equals("/")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "1");
            }
        }else if(!(nextNum.equals("0"))&&digitlength<=8&& Opr.equals("None")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "1");
            }
        }
    }//GEN-LAST:event_JBtnNum1ActionPerformed

    private void JBtnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnNum2ActionPerformed
        // TODO add your handling code here:
        
        String Length = JLabelLength.getText();
        if(Length.equals("0")){
            JTextResult.setText("2");
        }
        
        String nextNum = JTextResult.getText();
        String Opr = JLabelOperation.getText();
        int digitlength = nextNum.length();
        String newdigitLength = String.valueOf(digitlength);
        JLabelLength.setText(newdigitLength);
        
        if(!(nextNum.equals("0"))&& Opr.equals("+")||Opr.equals("-")||Opr.equals("*")||Opr.equals("/")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "2");
            }
        }else if(!(nextNum.equals("0"))&&digitlength<=8&& Opr.equals("None")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "2");
            }
        }
    }//GEN-LAST:event_JBtnNum2ActionPerformed

    private void JBtnNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnNum4ActionPerformed
        // TODO add your handling code here:
        String Length = JLabelLength.getText();
        if(Length.equals("0")){
            JTextResult.setText("4");
        }
        
        String nextNum = JTextResult.getText();
        String Opr = JLabelOperation.getText();
        int digitlength = nextNum.length();
        String newdigitLength = String.valueOf(digitlength);
        JLabelLength.setText(newdigitLength);
        if(!(nextNum.equals("0"))&& Opr.equals("+")||Opr.equals("-")||Opr.equals("*")||Opr.equals("/")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "4");
            }
        }else if(!(nextNum.equals("0"))&&digitlength<=8&& Opr.equals("None")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "4");
            }
        }
    }//GEN-LAST:event_JBtnNum4ActionPerformed

    private void JBtnNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnNum5ActionPerformed
        // TODO add your handling code here:
       String Length = JLabelLength.getText();
        if(Length.equals("0")){
            JTextResult.setText("5");
        }
        
        String nextNum = JTextResult.getText();
        String Opr = JLabelOperation.getText();
        int digitlength = nextNum.length();
        String newdigitLength = String.valueOf(digitlength);
        JLabelLength.setText(newdigitLength)
                ;
        if(!(nextNum.equals("0"))&& Opr.equals("+")||Opr.equals("-")||Opr.equals("*")||Opr.equals("/")){
                    
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "5");
            }
            
        }else if(!(nextNum.equals("0"))&&digitlength<=8&& Opr.equals("None")){
               
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "5");
            }
               
        }
    }//GEN-LAST:event_JBtnNum5ActionPerformed

    private void JBtnNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnNum6ActionPerformed
        // TODO add your handling code here:
        String Length = JLabelLength.getText();
        if(Length.equals("0")){
            JTextResult.setText("6");
        }
        
        String nextNum = JTextResult.getText();
        String Opr = JLabelOperation.getText();
        int digitlength = nextNum.length();
        String newdigitLength = String.valueOf(digitlength);
        JLabelLength.setText(newdigitLength);
        
        if(!(nextNum.equals("0"))&& Opr.equals("+")||Opr.equals("-")||Opr.equals("*")||Opr.equals("/")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "6");
            }
        }else if(!(nextNum.equals("0"))&&digitlength<=8&& Opr.equals("None")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "6");
            }
        }
    }//GEN-LAST:event_JBtnNum6ActionPerformed

    private void JBtnNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnNum7ActionPerformed
        // TODO add your handling code here:
        String Length = JLabelLength.getText();
        if(Length.equals("0")){
            JTextResult.setText("7");
        }
        
        String nextNum = JTextResult.getText();
        String Opr = JLabelOperation.getText();
        int digitlength = nextNum.length();
        String newdigitLength = String.valueOf(digitlength);
        JLabelLength.setText(newdigitLength);
        
        if(!(nextNum.equals("0"))&& Opr.equals("+")||Opr.equals("-")||Opr.equals("*")||Opr.equals("/")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "7");
            }
        }else if(!(nextNum.equals("0"))&&digitlength<=8&& Opr.equals("None")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "7");
            }
        }
    }//GEN-LAST:event_JBtnNum7ActionPerformed

    private void JBtnNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnNum8ActionPerformed
        // TODO add your handling code here:
        String Length = JLabelLength.getText();
        if(Length.equals("0")){
            JTextResult.setText("8");
        }
        
        String nextNum = JTextResult.getText();
        String Opr = JLabelOperation.getText();
        int digitlength = nextNum.length();
        String newdigitLength = String.valueOf(digitlength);
        JLabelLength.setText(newdigitLength);
        
        if(!(nextNum.equals("0"))&& Opr.equals("+")||Opr.equals("-")||Opr.equals("*")||Opr.equals("/")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "8");
            }
        }else if(!(nextNum.equals("0"))&&digitlength<=8&& Opr.equals("None")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "8");
            }
        }
    }//GEN-LAST:event_JBtnNum8ActionPerformed

    private void JBtnNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnNum9ActionPerformed
        // TODO add your handling code here:
        String Length = JLabelLength.getText();
        if(Length.equals("0")){
            JTextResult.setText("9");
        }
        
        String nextNum = JTextResult.getText();
        String Opr = JLabelOperation.getText();
        int digitlength = nextNum.length();
        String newdigitLength = String.valueOf(digitlength);
        JLabelLength.setText(newdigitLength);
        
        if(!(nextNum.equals("0"))&& Opr.equals("+")||Opr.equals("-")||Opr.equals("*")||Opr.equals("/")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "9");
            }
        }else if(!(nextNum.equals("0"))&&digitlength<=8&& Opr.equals("None")){
            if(digitlength==8){
                 JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "9");
            }
        }
    }//GEN-LAST:event_JBtnNum9ActionPerformed

    private void JBtnNum00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnNum00ActionPerformed
        // TODO add your handling code here:
        String Length = JLabelLength.getText();
        if(Length.equals("0")){
            JTextResult.setText("0");
        }
        String nextNum = JTextResult.getText();
        String Opr = JLabelOperation.getText();
        int digitlength = nextNum.length();
        String newdigitLength = String.valueOf(digitlength);
        JLabelLength.setText(newdigitLength);
        if(!(nextNum.equals("0"))&& Opr.equals("+")||Opr.equals("-")||Opr.equals("*")||Opr.equals("/")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "00");
            }       
        }else if(!(nextNum.equals("0"))&&digitlength<=8&& Opr.equals("None")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "00");
            } 
        }
    }//GEN-LAST:event_JBtnNum00ActionPerformed

    private void JBtnNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnNum0ActionPerformed
        // TODO add your handling code here:
       String Length = JLabelLength.getText();
        if(Length.equals("0")){
            JTextResult.setText("0");
        }
        
        String nextNum = JTextResult.getText();
        String Opr = JLabelOperation.getText();
        int digitlength = nextNum.length();
        String newdigitLength = String.valueOf(digitlength);
        JLabelLength.setText(newdigitLength);
        
        if(!(nextNum.equals("0"))&& Opr.equals("+")||Opr.equals("-")||Opr.equals("*")||Opr.equals("/")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "0");
            }
        }else if(!(nextNum.equals("0"))&&digitlength<=8&& Opr.equals("None")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0")) && digitlength!=8){ 
                JTextResult.setText(nextNum + "0");
            }
        }
    }//GEN-LAST:event_JBtnNum0ActionPerformed

    private void JBtnDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnDecimalActionPerformed
        // TODO add your handling code here:
        
        String nextNum = JTextResult.getText();
        String floatActive = JLabelFloat.getText();
        
        if(floatActive.equals("false")){
            if(nextNum.equals("0")){
                JTextResult.setText("0.");
            }else{
                JTextResult.setText(nextNum + ".");
                JLabelFloat.setText("true");
            }
        }else{
            JTextResult.setText(nextNum);
        }
        
    }//GEN-LAST:event_JBtnDecimalActionPerformed

    private void JBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnDeleteActionPerformed
        // TODO add your handling code here:
        
        String nextNum = JTextResult.getText();
        char[] resultLength = nextNum.toCharArray();
        int digitLength = resultLength.length;
        
        if(digitLength==1){
            JTextResult.setText("0");
            JLabelLength.setText("0");
        }else{
            digitLength--;
            String newDigitLength = nextNum.substring(0, digitLength);
            JTextResult.setText(newDigitLength);
        }
        
    }//GEN-LAST:event_JBtnDeleteActionPerformed

    private void JBtnAllClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAllClearActionPerformed
        // TODO add your handling code here:
        JTextResult.setText("0");
        JLabelOperation.setText("None");
        JLabelLength.setText("0");
        JLabelFnum.setText("0");
    }//GEN-LAST:event_JBtnAllClearActionPerformed

    private void JBtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAddActionPerformed
        // TODO add your handling code here:

        String fnum = JTextResult.getText();
        JLabelFnum.setText(fnum);
        JLabelOperation.setText("+");
        JLabelLength.setText("0");
        
    }//GEN-LAST:event_JBtnAddActionPerformed

    private void JBtnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnDivideActionPerformed
        // TODO add your handling code here:
        String fnum = JTextResult.getText();
        JLabelFnum.setText(fnum);
        JLabelOperation.setText("/");
        JLabelLength.setText("0");
    }//GEN-LAST:event_JBtnDivideActionPerformed

    private void JBtnSubstractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnSubstractActionPerformed
        // TODO add your handling code here:
       String fnum = JTextResult.getText();
        JLabelFnum.setText(fnum);
        JLabelOperation.setText("-");
        JLabelLength.setText("0");
    }//GEN-LAST:event_JBtnSubstractActionPerformed

    private void JBtnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnMultiplyActionPerformed
        // TODO add your handling code here:
        String fnum = JTextResult.getText();
        JLabelFnum.setText(fnum);
        JLabelOperation.setText("*");
        JLabelLength.setText("0");
    }//GEN-LAST:event_JBtnMultiplyActionPerformed

    private void JBtnNum1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JBtnNum1KeyTyped
        // TODO add your handling code here:
        String Length = JLabelLength.getText();
        if(Length.equals("0")){
            JTextResult.setText("1");
        }
        
        String nextNum = JTextResult.getText();
        String Opr = JLabelOperation.getText();
        int digitlength = nextNum.length();
        String newdigitLength = String.valueOf(digitlength);
        JLabelLength.setText(newdigitLength);
        
        if(!(nextNum.equals("0"))&& Opr.equals("+")||Opr.equals("-")||Opr.equals("*")||Opr.equals("/")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "1");
            }
        }else if(!(nextNum.equals("0"))&&digitlength<=8&& Opr.equals("None")){
            if(digitlength==8){
                JTextResult.setText(nextNum);
            }else if(!(Length.equals("0"))&&digitlength!=8){ 
                JTextResult.setText(nextNum + "1");
            }
        }
    }//GEN-LAST:event_JBtnNum1KeyTyped

    private void JBtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnEqualActionPerformed
        // TODO add your handling code here:
        String snum = JTextResult.getText();
        int snum1 = Integer.parseInt(snum);
        String fnum = JLabelFnum.getText();
        int fnum1 = Integer.parseInt(fnum);

        String Operation = JLabelOperation.getText();

        switch (Operation) {
            case "+":
            String floatActive = JLabelFloat.getText();
            String sum1;
				if(floatActive.equals("true")){
					float sum = fnum1 + snum1;
					sum1 = String.valueOf(sum);
				}else{
					int sum = fnum1 + snum1;
					sum1 = String.valueOf(sum);
				}
				
				int digitLength = sum1.length();
				if(digitLength<=8){
					//String sumResultLength = sum1.substring(1,8);
					JTextResult.setText(sum1);
					JLabelFnum.setText(sum1);
					JLabelOperation.setText("None");
					JLabelLength.setText("0");
				}else{
					String sumResultLength = sum1.substring(1,8);
					JTextResult.setText(sumResultLength);
					JLabelFnum.setText(sumResultLength);
					JLabelOperation.setText("None");
					JLabelLength.setText("0");
				}
				break;
            
            case "-":
				floatActive = JLabelFloat.getText();
				String diff1;
				if(floatActive.equals("true")){
					float diff = fnum1 + snum1;
					diff1 = String.valueOf(diff);
				}else{    
					int diff = fnum1 - snum1;
					diff1 = String.valueOf(diff);
				}
				
				digitLength = diff1.length();
				if(digitLength<=8){
					JTextResult.setText(diff1);
					JLabelFnum.setText(diff1);
					JLabelOperation.setText("None");
					JLabelLength.setText("0");
				}else{
					String diffResultLength = diff1.substring(1,8);
					JTextResult.setText(diffResultLength);
					JLabelFnum.setText(diffResultLength);
					JLabelOperation.setText("None");
					JLabelLength.setText("0");
				}
				break;
            
            case "*":
				int prod = fnum1 * snum1;
				String prod1 = String.valueOf(prod);
				digitLength = prod1.length();
				if(digitLength<=8){
					JTextResult.setText(prod1);
					JLabelFnum.setText(prod1);
					JLabelOperation.setText("None");
					JLabelLength.setText("0");
				}else{
					String prodResultLength = prod1.substring(1,8);
					JTextResult.setText(prodResultLength);
					JLabelFnum.setText(prodResultLength);
					JLabelOperation.setText("None");
					JLabelLength.setText("0");
				}
            break;
            
            case "/":
				int qout = fnum1 / snum1;
				String qout1 = String.valueOf(qout);
				digitLength = qout1.length();
				if(digitLength<=8){
					int remainder = fnum1%snum1;
					String remainder1 = String.valueOf(remainder);
					if(remainder==0){
						JTextResult.setText(qout1);
						JLabelFnum.setText(qout1);
					}else{
						JTextResult.setText(qout1 + "." + remainder1);
						JLabelFnum.setText(qout1 + "." + remainder1);
					}
					JLabelOperation.setText("None");
					JLabelLength.setText("0");
				}else{
					String qoutResultLength = qout1.substring(1,8);
					JTextResult.setText(qoutResultLength);
					JLabelFnum.setText(qoutResultLength);
					JLabelOperation.setText("None");
					JLabelLength.setText("0");
				}
				break;
            
            default:
                break;
        }
    }//GEN-LAST:event_JBtnEqualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dracula".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CalculatorApp().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtnAdd;
    private javax.swing.JButton JBtnAllClear;
    private javax.swing.JButton JBtnDecimal;
    private javax.swing.JButton JBtnDelete;
    private javax.swing.JButton JBtnDivide;
    private javax.swing.JButton JBtnEqual;
    private javax.swing.JButton JBtnMultiply;
    private javax.swing.JButton JBtnNum0;
    private javax.swing.JButton JBtnNum00;
    private javax.swing.JButton JBtnNum1;
    private javax.swing.JButton JBtnNum2;
    private javax.swing.JButton JBtnNum3;
    private javax.swing.JButton JBtnNum4;
    private javax.swing.JButton JBtnNum5;
    private javax.swing.JButton JBtnNum6;
    private javax.swing.JButton JBtnNum7;
    private javax.swing.JButton JBtnNum8;
    private javax.swing.JButton JBtnNum9;
    private javax.swing.JButton JBtnSubstract;
    private javax.swing.JLabel JLabelFloat;
    private javax.swing.JLabel JLabelFnum;
    private javax.swing.JLabel JLabelLength;
    private javax.swing.JLabel JLabelOperation;
    private javax.swing.JTextField JTextResult;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
